//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnipiLabs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        public int primKeyID { get; set; }
        public string subjectID { get; set; }
        public string labID { get; set; }
        public int teamID { get; set; }
        public string selectedExamSlot { get; set; }
        public string teamMembers { get; set; }
        public DateTime AddedOn { get; internal set; }
    }
}
