//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnipiLabs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public string ID { get; set; }
        public string subjRegistered { get; set; }
        public string examsRegistered { get; set; }
        public int teamID { get; set; }
        public string teamMembers { get; set; }
    }
}
